### ISSUE TITLE
Is this a functional codebase?

### ISSUE THREAD

**Issue by cyrilzakka** [zhangjinsong3/SOLOv2.tensorRT#1]
Hello!
I was wondering if this codebase actually worked. If so, any ideas on the new mAP, size and inference speed of the SOLOV2 model?

**Comment by zhangjinsong3** [comment]
Yes.Most code can be seen in the folder “deploy”，including some speed and result comparisons



---Original---
From: "Cyril ***@***.***&gt;
Date: Sun, May 23, 2021 03:52 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [zhangjinsong3/SOLOv2.tensorRT] Is this a functional codebase? (#1)




 
Hello!
 I was wondering if this codebase actually worked. If so, any ideas on the new mAP, size and inference speed of the SOLOV2 model?

**Comment by cyrilzakka** [comment]
Oh wow, I've been looking for this for a while! Two more questions:
1 - In order to train my model, can I do so on the original codebase and then convert it using the scripts here? Or does everything need to happen through here?

2 - I can't seem to find mAP values in deploy, only ms and GPU size. Would you mind pointing me in the right direction? 

Again, thank you and really appreciate your work!

**Comment by zhangjinsong3** [comment]
1.Training on original author's codebase is ok. The difference happen only during the inference process
2.As u can seen in the “deploy/images” folder, the result between torch with onnxruntime or tensorrt is almost the same. Thus the mAP should be the same.



---Original---
From: "Cyril ***@***.***&gt;
Date: Sun, May 23, 2021 15:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhangjinsong3/SOLOv2.tensorRT] Is this a functional codebase? (#1)




 
Oh wow, I've been looking for this for a while! Two more questions:
 1 - In order to train my model, can I do so on the original codebase and then convert it using the scripts here? Or does everything need to happen through here?
 
2 - I can't seem to find mAP values in deploy, only ms and GPU size. Would you mind pointing me in the right direction?
 
Again, thank you and really appreciate your work!

**Comment by cyrilzakka** [comment]
That's amazing, thank you! If I wanted to cite this codebase in a paper, how would you like me to do it?

**Comment by zhangjinsong3** [comment]
Wow,It's my pleasure to get an simple quote in your paper. All of the code based on original SOLO. That is the main contribution.




---Original---
From: "Cyril ***@***.***&gt;
Date: Sun, May 23, 2021 17:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhangjinsong3/SOLOv2.tensorRT] Is this a functional codebase? (#1)




 
That's amazing, thank you! If I wanted to cite this codebase in a paper, how would you like me to do it?
